scanner:
    diff_only: False
    linter: pycodestyle

pycodestyle:
    exclude:
        - Contents/Libraries/Shared
    ignore:
        - E501  # line too long
        - E722  # do not use bare 'except'
